## Reading Extended Backus-Naur Form (EBNF) Notation:
# expression = value
# * means 0 or more times
# + means one or more times
# | indicates an alternative
# () group statements
# ? means optional
# [...] means a character class (regex-esque)
# [^...] means a negated character class (regex-esque)
# {n} means exactly n repetitions

#~ Basics

translation_unit =
    module_statement?
    import_statement*
    statement*

single_line_comment = "#" [^\n]*
multi_line_comment = "/*" ([^*] | "*" [^/] | multi_line_comment)* "*/"

letter = 'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'G' | 
         'H' | 'I' | 'J' | 'K' | 'L' | 'M' | 'N' | 
         'O' | 'P' | 'Q' | 'R' | 'S' | 'T' | 'U' | 
         'V' | 'W' | 'X' | 'Y' | 'Z' | 'a' | 'b' | 
         'c' | 'd' | 'e' | 'f' | 'g' | 'h' | 'i' | 
         'j' | 'k' | 'l' | 'm' | 'n' | 'o' | 'p' | 
         'q' | 'r' | 's' | 't' | 'u' | 'v' | 'w' | 
         'x' | 'y' | 'z'

binary_digit = '0' | '1'
octal_digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7'
decimal_digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' 
hexadecimal_digit = '0' | '1' | '2' | '3' | '4' | '5' | '6' | '7' | '8' | '9' | 
                    'A' | 'B' | 'C' | 'D' | 'E' | 'F' | 'a' | 'b' | 'c' | 'd' | 'e' | 'f'

binary_integer_literal = "0b" binary_digit+
octal_integer_literal = "0o" octal_digit+
decimal_integer_literal = decimal_digit+
hexadecimal_integer_literal = "0x" hexadecimal_digit+

integer_suffix = "i8" | "i16" | "i32" | "i64" | "i128" | "u8" | "u16" | "u32" | "u64" | "u128" | 
                 "I8" | "I16" | "I32" | "I64" | "I128" | "U8" | "U16" | "U32" | "U64" | "U128"

floating_point_suffix = "f32" | "f64" | "F32" | "F64"

exponent = ("e" | "E") ("+" | "-")? decimal_digit+

integer_literal = (binary_integer_literal | octal_integer_literal | decimal_integer_literal | hexadecimal_integer_literal) integer_suffix?

floating_point_literal = decimal_digit+ "." decimal_digit* exponent? floating_point_suffix?

boolean_literal = "true" | "false"

unicode_escape_sequence = ("u" | "U") (hexadecimal_digit{4} | hexadecimal_digit{8})

escape_sequence =
    "\\" (
        "'"
      | '"'
      | "\\"
      | "a"
      | "b"
      | "f"
      | "n"
      | "r"
      | "t"
      | "v"
      | "0"
      | unicode_escape_sequence
    )

array_literal = ("[" expression ("," expression)* "]") | ("[" "]")

identifier = (letter | "_") (letter | decimal_digit | "_")*

whitespace = " " | "\t" | "\r" | "\n"

character = [^'\\\n\r] | escape_sequence
string_character = [^"\\\n\r] | escape_sequence

character_literal = "'" character "'"
string_literal = '"' string_character* '"'

access_modifier = "public" | "private"

#~ Operators

# lexer uses maximal munch (so >>= becomes >>=, not three separate tokens)

arithmetic_operator = "+" | "-" | "*" | "/" | "//" | "%"
assignment_operator = "+=" | "-=" | "*=" | "/=" | "//=" | "%=" | "&=" | "|=" | "^=" | "<<=" | ">>="
bitwise_operator = "&" | "|" | "~" | "^" | "<<" | ">>"
relational_operator = "<" | "<=" | ">" | ">=" | "==" | "!="
logical_operator = "&&" | "||" | "!"
postfix_operator = "++" | "--"
prefix_operator = "++" | "--" | "!" | "-" | "&" | "*"

binary_operator =
      arithmetic_operator
    | "&"
    | "|"
    | "^"
    | "<<"
    | ">>"
    | relational_operator
    | "&&"
    | "||"

#~ Punctuators

left_paren = "("
right_paren = ")"
left_bracket = "["
right_bracket = "]"
left_brace = "{"
right_brace = "}"
comma = ","
semicolon = ";"
colon = ":"
at = "@"
arrow = "->"
ellipsis = "..."

punctuator = left_paren | right_paren | left_bracket | right_bracket | left_brace | right_brace | comma | semicolon | colon | at | arrow | ellipsis

#~ Expressions

expression =
      assignment_expression
    | binary_expression
    | type_cast_expression
    | prefix_expression
    | postfix_expression
    | function_call_expression
    | generic_expression
    | index_expression
    | member_access_expression
    | scope_resolution_expression
    | sizeof_expression
    | alignof_expression
    | identifier_expression
    | number_literal_expression
    | bool_literal_expression
    | char_literal_expression
    | string_literal_expression
    | array_literal_expression
    | aggregate_literal_expression
    | aggregate_instantiation_expression
    | "(" expression ")"


assignment_expression = expression assignment_operator expression

binary_expression = expression binary_operator expression

bool_literal_expression = boolean_literal

char_literal_expression = character_literal

type_cast_expression = expression "as" type

prefix_expression = prefix_operator expression

postfix_expression = expression postfix_operator

function_call_expression = expression "(" (expression ("," expression)*)? ")"

generic_expression = expression "@[" type ("," type)* "]"

index_expression = expression "[" expression "]"

member_access_expression = expression "." identifier

number_literal_expression = integer_literal | floating_point_literal

scope_resolution_expression = expression "::" identifier

sizeof_expression = "sizeof" "(" type ")"

alignof_expression = "alignof" "(" type ")"

identifier_expression = identifier

string_literal_expression = string_literal

array_literal_expression = array_literal

aggregate_literal_expression =
    "aggregate" "{"
        (expression ("," expression)*)?
    "}"

aggregate_instantiation_expression =
    identifier ("@[" type ("," type)* "]")?
    "{"
        (identifier "=" expression ("," identifier "=" expression)*)?
    "}"

#~ Statements

statement =
      declaration_statement
    | control_flow_statement
    | expression_statement
    | nested_block_statement
    | empty_statement

##~ Declarations

declaration_statement =
      aggregate_declaration_statement
    | alias_statement
    | enum_declaration_statement
    | function_declaration_statement
    | variable_declaration_statement


aggregate_declaration_statement =
    access_modifier? "aggregate" identifier generic_parameter_list? "{"
        aggregate_member*
    "}"

aggregate_member = identifier ":" type ";"

alias_statement = access_modifier? "alias" identifier "=" type ";"

enum_member = identifier ("=" expression)?

enum_declaration_statement =
    access_modifier? "enum" identifier ":" type "{"
        enum_member ("," enum_member)* ","?
    "}"

function_declaration_statement =
    access_modifier? "func" identifier generic_parameter_list?
    "(" parameter_list? ")" ("->" type)?
    block

parameter_list =
      parameter ("," parameter)* ("," variadic_parameter)?
    | variadic_parameter

parameter = identifier ":" type ("=" expression)?

variadic_parameter = identifier "..." ":" type

# semantically, variable declaration needs a type or an expression

variable_declaration = "let" identifier (":" "mut"? type) ("=" expression)?

variable_declaration_statement = variable_declaration ";"

generic_parameter_list =
    generic_parameter ("," generic_parameter)*

generic_parameter = identifier

#~ Control Flow

control_flow_statement =
      break_statement
    | continue_statement
    | for_loop_statement
    | if_statement
    | return_statement
    | switch_statement
    | while_loop_statement

break_statement = "break" ";"
continue_statement = "continue" ";"

for_loop_statement =
    "for" "("
        for_initializer?
        ";"
        expression?
        ";"
        expression?
    ")"
    block

for_initializer =
      variable_declaration
    | expression

if_statement =
    "if" "(" expression ")" block
    ("elif" "(" expression ")" block)*
    ("else" block)?

return_statement = "return" expression? ";"

switch_statement =
    "switch" "(" expression ")" "{"
        switch_case*
        switch_default?
    "}"

switch_case = "case" expression ":" statement*

switch_default = "default" ":" statement*

while_loop_statement =
      "while" "(" expression ")" block
    | "do" block "while" "(" expression ")" ";"

#~ Other Statements

expression_statement = expression ";"

nested_block_statement = block

block = "{" statement* "}"

empty_statement = ";"

#~ Types

type =
      aggregate_type
    | array_type
    | function_type
    | generic_type
    | pointer_type
    | scoped_type
    | symbol_type
    | typeof_type


aggregate_type =
    "aggregate" "{"
        (type ("," type)*)?
    "}"

array_type = type "[" expression? "]"

function_type = "func" "(" function_type_parameter_list? ")" ("->" type)?

function_type_parameter_list =
    function_type_parameter
    ("," function_type_parameter)*
    ("," function_type_variadic_parameter)?

function_type_parameter = type

function_type_variadic_parameter = type "..."

generic_type = generic_base "@[" type ("," type)* "]"

generic_base = symbol_type | scoped_type


pointer_type = "mut"? "ptr" type

scoped_type = identifier ("::" identifier)+

symbol_type = identifier

typeof_type = "typeof" "(" expression ")"

#~ Modules and Imports

import_statement =
    "import"
    identifier ("::" identifier)*
    ("as" identifier)?
    ";"

module_statement = "module" identifier ";"
